# Generated by Django 3.1.7 on 2021-03-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woven', '0002_auto_20210228_0033'),
        ('woven', '0002_apirequest'),
    ]

    operations = [
    ]
