# Generated by Django 3.1.7 on 2021-03-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=400)),
                ('end_time', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('successful', 'successful'), ('failed', 'failed')], max_length=100)),
                ('status_message', models.JSONField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
